# Generated by Django 4.0.3 on 2022-04-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('twitter', models.CharField(default='', max_length=200, verbose_name='twitter')),
                ('youtube', models.CharField(default='', max_length=200, verbose_name='youtube')),
                ('twitch', models.CharField(default='', max_length=200, verbose_name='twitch')),
            ],
        ),
    ]
