# Generated by Django 4.0.3 on 2022-04-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='twitch',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='twitch'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='youtube'),
        ),
    ]
