# Generated by Django 4.0.3 on 2022-04-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_alter_speaker_twitch_alter_speaker_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Linkedin'),
        ),
    ]
