# Generated by Django 4.0.3 on 2022-04-04 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconnaissance',
            name='company',
            field=models.CharField(
                default='', max_length=200, verbose_name='Compania'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='country',
            field=models.CharField(
                default='', max_length=200, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='email',
            field=models.EmailField(
                default='', max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='gender',
            field=models.CharField(
                default='', max_length=200, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='has_newsletter',
            field=models.BooleanField(
                default=True, max_length=200, verbose_name='Newsletter'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='mode',
            field=models.CharField(
                default='', max_length=200, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='region',
            field=models.CharField(
                default='', max_length=200, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='seniority',
            field=models.CharField(
                default='', max_length=200, verbose_name='Seniority'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='speakers_raw',
            field=models.CharField(
                default='', max_length=200, verbose_name='Speakers'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='submitted_at',
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Submit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='tendency_raw',
            field=models.CharField(
                default='', max_length=200, verbose_name='Tendency'),
        ),
        migrations.AlterField(
            model_name='reconnaissance',
            name='name',
            field=models.CharField(
                default='', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='reconnaissance',
            name='survey_id',
            field=models.CharField(
                default='', max_length=200, verbose_name='Encuesta User id'),
        ),
    ]
