# Generated by Django 4.0.3 on 2022-04-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconnaissance',
            name='company',
            field=models.CharField(default='', max_length=200, verbose_name='Compania'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='country',
            field=models.CharField(default='', max_length=200, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='email',
            field=models.EmailField(default='', max_length=200, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='gender',
            field=models.CharField(default='', max_length=200, verbose_name='Genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='has_newsletter',
            field=models.BooleanField(default=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='mode',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='region',
            field=models.CharField(default='', max_length=200, verbose_name='Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='seniority',
            field=models.CharField(default='', max_length=200, verbose_name='Seniority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='speakers_raw',
            field=models.CharField(default='', max_length=200, verbose_name='Speakers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='submitted_at',
            field=models.DateField(default='', max_length=200, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='tendency_raw',
            field=models.CharField(default='', max_length=200, verbose_name='Tendency'),
            preserve_default=False,
        ),
    ]
