# Generated by Django 4.0.3 on 2022-04-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissances', '0002_reconnaissance_company_reconnaissance_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconnaissance',
            name='survey_id',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Encuesta User id'),
        ),
    ]
