# Generated by Django 4.0.3 on 2022-04-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_alter_speaker_twitch_alter_speaker_twitter_and_more'),
        ('reconnaissances', '0004_reconnaissance_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconnaissance',
            name='speaker',
            field=models.ManyToManyField(blank=True, to='speakers.speaker'),
        ),
    ]
