# Generated by Django 4.0.3 on 2022-04-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissances', '0005_alter_reconnaissance_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconnaissance',
            name='region',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Region'),
        ),
    ]
