# Generated by Django 4.0.3 on 2022-04-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissances', '0006_alter_reconnaissance_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconnaissance',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Compania'),
        ),
        migrations.AlterField(
            model_name='reconnaissance',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='reconnaissance',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reconnaissance',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='reconnaissance',
            name='seniority',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Seniority'),
        ),
        migrations.AlterField(
            model_name='reconnaissance',
            name='speakers_raw',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Speakers'),
        ),
        migrations.AlterField(
            model_name='reconnaissance',
            name='tendency_raw',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Tendency'),
        ),
    ]
