# Generated by Django 4.0.3 on 2022-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('reconnaissances', '0009_rename_company_reconnaissance_company_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconnaissance',
            name='company',
            field=models.ManyToManyField(blank=True, to='companies.company'),
        ),
    ]
