# Generated by Django 4.0.3 on 2022-04-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_speaker_linkedin'),
        ('companies', '0001_initial'),
        ('reconnaissances', '0010_reconnaissance_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconnaissance',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='reconnaissance',
            name='speaker',
            field=models.ManyToManyField(blank=True, null=True, to='speakers.speaker'),
        ),
    ]
